-- MySQL Script generated by MySQL Workbench
-- Fri Sep 17 19:19:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Addetto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addetto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Addetto` (
  `idAddetto` INT NOT NULL AUTO_INCREMENT COMMENT 'Detto anche Matricola',
  `Nome` VARCHAR(255) NULL,
  `Cognome` VARCHAR(255) NULL,
  `Store` INT NULL,
  PRIMARY KEY (`idAddetto`),
  INDEX `fk_Addetto_Store1_idx` (`Store` ASC) VISIBLE,
  CONSTRAINT `fk_Addetto_Store1`
    FOREIGN KEY (`Store`)
    REFERENCES `mydb`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Store` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Store` (
  `idStore` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `Responsabile` INT NULL,
  PRIMARY KEY (`idStore`),
  INDEX `fk_Store_Addetto1_idx` (`Responsabile` ASC) VISIBLE,
  CONSTRAINT `fk_Store_Addetto1`
    FOREIGN KEY (`Responsabile`)
    REFERENCES `mydb`.`Addetto` (`idAddetto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Video` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `idVideo` INT NOT NULL AUTO_INCREMENT,
  `Titolo` VARCHAR(255) NULL,
  `Regista` VARCHAR(255) NULL,
  `Casa` VARCHAR(255) NULL,
  `Durata` INT NULL,
  `Genere` VARCHAR(255) NULL,
  `Fornitore` VARCHAR(255) NULL,
  `DataScadenza` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idVideo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL,
  `Cognome` VARCHAR(255) NULL,
  `Indirizzo` VARCHAR(255) NULL,
  `Telefono` VARCHAR(25) NULL,
  `Cellulare` VARCHAR(25) NULL,
  `Email` VARCHAR(255) NULL,
  `Nascita` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Liberatoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Liberatoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Liberatoria` (
  `Customer` INT NOT NULL,
  `Coordinate` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Customer`),
  INDEX `fk_Liberatoria_Customer1_idx` (`Customer` ASC) VISIBLE,
  CONSTRAINT `fk_Liberatoria_Customer1`
    FOREIGN KEY (`Customer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Noleggia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Noleggia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Noleggia` (
  `idNoleggio` INT NOT NULL AUTO_INCREMENT,
  `DataInizio` TIMESTAMP NOT NULL,
  `DataFine` TIMESTAMP NOT NULL,
  `Video` INT NOT NULL,
  `Customer` INT NOT NULL,
  `Tariffa` DECIMAL(2) NOT NULL,
  `Addetto` INT NOT NULL,
  PRIMARY KEY (`idNoleggio`),
  INDEX `fk_Noleggia_Video1_idx` (`Video` ASC) VISIBLE,
  INDEX `fk_Noleggia_Customer1_idx` (`Customer` ASC) VISIBLE,
  INDEX `fk_Noleggia_Addetto1_idx` (`Addetto` ASC) VISIBLE,
  CONSTRAINT `fk_Noleggia_Video1`
    FOREIGN KEY (`Video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noleggia_Customer1`
    FOREIGN KEY (`Customer`)
    REFERENCES `mydb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Noleggia_Addetto1`
    FOREIGN KEY (`Addetto`)
    REFERENCES `mydb`.`Addetto` (`idAddetto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Disponibilita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disponibilita` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibilita` (
  `Quantita` INT NOT NULL,
  `Store_idStore` INT NOT NULL,
  `Video_idVideo` INT NOT NULL,
  PRIMARY KEY (`Store_idStore`, `Video_idVideo`),
  INDEX `fk_Disponibilita_Video1_idx` (`Video_idVideo` ASC) VISIBLE,
  CONSTRAINT `fk_Disponibilita_Store1`
    FOREIGN KEY (`Store_idStore`)
    REFERENCES `mydb`.`Store` (`idStore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disponibilita_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Addetto`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Addetto` (`idAddetto`, `Nome`, `Cognome`, `Store`) VALUES (1, 'Nicola', 'Bernardini', 1);
INSERT INTO `mydb`.`Addetto` (`idAddetto`, `Nome`, `Cognome`, `Store`) VALUES (2, 'Samantha', 'Scapece', 1);
INSERT INTO `mydb`.`Addetto` (`idAddetto`, `Nome`, `Cognome`, `Store`) VALUES (3, 'Mimmo', 'Molisani', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Store`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Store` (`idStore`, `name`, `Responsabile`) VALUES (1, 'Appia Nuova Video Store', 1);
INSERT INTO `mydb`.`Store` (`idStore`, `name`, `Responsabile`) VALUES (2, 'Colle Martino Store', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Video`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Video` (`idVideo`, `Titolo`, `Regista`, `Casa`, `Durata`, `Genere`, `Fornitore`, `DataScadenza`) VALUES (1, 'Stargate', 'James Carry', 'Paramount', 125, 'Sci-fi', '1', '30/09/2021');
INSERT INTO `mydb`.`Video` (`idVideo`, `Titolo`, `Regista`, `Casa`, `Durata`, `Genere`, `Fornitore`, `DataScadenza`) VALUES (2, 'Stargate - Ark of truth', 'James Carry', 'Paramount', 78, 'Sci-fi', '1', '30/09/2021');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Customer` (`idCustomer`, `Nome`, `Cognome`, `Indirizzo`, `Telefono`, `Cellulare`, `Email`, `Nascita`) VALUES (1, 'Gino', 'Paoli', 'Bivio dei ciliegi, 44, Roma (RM)', '060511475', '3475512069', NULL, '2000/01/05');
INSERT INTO `mydb`.`Customer` (`idCustomer`, `Nome`, `Cognome`, `Indirizzo`, `Telefono`, `Cellulare`, `Email`, `Nascita`) VALUES (2, 'Leonardo', 'Da Vinci', 'Via del carro, 3, Torino ()', '053212493', '3195502033', 'leo.da.vinci@gmail.com', '1947/11/30');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Liberatoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Liberatoria` (`Customer`, `Coordinate`) VALUES (1, 'AAA-001');
INSERT INTO `mydb`.`Liberatoria` (`Customer`, `Coordinate`) VALUES (2, 'AAA-002');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
